// cmd/cli/templates/frontend/vue/client/src/components/Layout.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div class="app">
    <header class="header">
      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </header>
    <main class="main">
      <RouterView />
    </main>
    <footer class="footer">
      <p>Built with Mizu + Vue</p>
    </footer>
  </div>
</template>

// cmd/cli/templates/frontend/reactrouter/client/app/routes/_layout.tsx
import { Link, Outlet } from "react-router";

export default function Layout() {
  return (
    <div className="app">
      <header className="header">
        <div className="header-content">
          <h1 className="logo">{{.Name}}</h1>
          <nav className="nav">
            <Link to="/" className="nav-link">Home</Link>
            <Link to="/about" className="nav-link">About</Link>
            <Link to="/users" className="nav-link">Users</Link>
          </nav>
        </div>
      </header>

      <main className="main">
        <Outlet />
      </main>

      <footer className="footer">
        <p>Built with Mizu + React Router v7</p>
      </footer>
    </div>
  );
}
