// cmd/cli/templates/frontend/spa/preact/client/src/components/Layout.tsx
import { ComponentChildren } from 'preact'

interface LayoutProps {
  children: ComponentChildren
}

function Layout({ children }: LayoutProps) {
  return (
    <div className="app">
      <header className="header">
        <nav>
          <a href="/">Home</a>
          <a href="/about">About</a>
        </nav>
      </header>
      <main className="main">
        {children}
      </main>
      <footer className="footer">
        <p>Built with Mizu + Preact</p>
      </footer>
    </div>
  )
}

export default Layout

// cmd/cli/templates/frontend/vue/client/src/components/Layout.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div class="app">
    <header class="header">
      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </header>
    <main class="main">
      <RouterView />
    </main>
    <footer class="footer">
      <p>Built with Mizu + Vue</p>
    </footer>
  </div>
</template>
