// cmd/cli/templates/frontend/react/frontend/src/components/Layout.tsx
import { Outlet, Link } from 'react-router-dom'

function Layout() {
  return (
    <div className="app">
      <header className="header">
        <nav>
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
        </nav>
      </header>
      <main className="main">
        <Outlet />
      </main>
      <footer className="footer">
        <p>Built with Mizu + React</p>
      </footer>
    </div>
  )
}

export default Layout

// cmd/cli/templates/frontend/vue/client/src/components/Layout.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div class="app">
    <header class="header">
      <nav>
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/about">About</RouterLink>
      </nav>
    </header>
    <main class="main">
      <RouterView />
    </main>
    <footer class="footer">
      <p>Built with Mizu + Vue</p>
    </footer>
  </div>
</template>
