// cmd/cli/templates/frontend/react/frontend/src/components/Layout.tsx
import { Outlet, Link } from 'react-router-dom'

function Layout() {
  return (
    <div className="app">
      <header className="header">
        <nav>
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
        </nav>
      </header>
      <main className="main">
        <Outlet />
      </main>
      <footer className="footer">
        <p>Built with Mizu + React</p>
      </footer>
    </div>
  )
}

export default Layout

// cmd/cli/templates/frontend/spa/angular/client/src/app/components/layout/layout.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';

@Component({
  selector: 'app-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink],
  templateUrl: './layout.component.html',
  styleUrl: './layout.component.css'
})
export class LayoutComponent {}

<div class="app">
  <header class="header">
    <nav>
      <a routerLink="/">Home</a>
      <a routerLink="/about">About</a>
    </nav>
  </header>
  <main class="main">
    <router-outlet></router-outlet>
  </main>
  <footer class="footer">
    <p>Built with Mizu + Angular</p>
  </footer>
</div>
