// cmd/cli/templates/frontend/react/client/src/pages/About.tsx
function About() {
  return (
    <div className="page about">
      <h1>About</h1>
      <p>
        This is a React SPA powered by Mizu, a lightweight Go web framework.
      </p>
      <ul>
        <li>React 18 with TypeScript</li>
        <li>Vite for fast development and optimized builds</li>
        <li>React Router for client-side routing</li>
        <li>Mizu backend with the frontend middleware</li>
      </ul>
    </div>
  )
}

export default About

// cmd/cli/templates/frontend/vue/client/src/pages/About.vue
<template>
  <div class="page about">
    <h1>About</h1>
    <p>
      This is a Vue SPA powered by Mizu, a lightweight Go web framework.
    </p>
    <ul>
      <li>Vue 3 with Composition API and TypeScript</li>
      <li>Vite for fast development and optimized builds</li>
      <li>Vue Router for client-side routing</li>
      <li>Mizu backend with the frontend middleware</li>
    </ul>
  </div>
</template>
