// cmd/cli/templates/frontend/spa/nuxt/client/pages/about.vue
<script setup lang="ts">
useHead({
  title: 'About - {{.Name}}',
})
</script>

<template>
  <div class="space-y-6">
    <h1 class="text-4xl font-bold">About</h1>
    <p class="text-slate-600">
      This is a Nuxt SPA powered by Mizu, a lightweight Go web framework.
    </p>
    <ul class="list-disc list-inside space-y-2 text-slate-600">
      <li>Nuxt 3 with TypeScript</li>
      <li>Static generation for SPA deployment</li>
      <li>File-based routing with auto-imports</li>
      <li>Tailwind CSS for styling</li>
      <li>Mizu backend with the frontend middleware</li>
    </ul>
  </div>
</template>

// cmd/cli/templates/frontend/spa/next/client/src/app/about/page.tsx
export default function About() {
  return (
    <div className="space-y-6">
      <h1 className="text-4xl font-bold">About</h1>
      <p className="text-slate-600">
        This is a Next.js SPA powered by Mizu, a lightweight Go web framework.
      </p>
      <ul className="list-disc list-inside space-y-2 text-slate-600">
        <li>Next.js 15 with App Router and TypeScript</li>
        <li>Static export for SPA deployment</li>
        <li>Tailwind CSS for styling</li>
        <li>Mizu backend with the frontend middleware</li>
      </ul>
    </div>
  )
}
