// cmd/cli/templates/frontend/react/frontend/src/components/Layout.tsx
import { Outlet, Link } from 'react-router-dom'

function Layout() {
  return (
    <div className="app">
      <header className="header">
        <nav>
          <Link to="/">Home</Link>
          <Link to="/about">About</Link>
        </nav>
      </header>
      <main className="main">
        <Outlet />
      </main>
      <footer className="footer">
        <p>Built with Mizu + React</p>
      </footer>
    </div>
  )
}

export default Layout

// cmd/cli/templates/frontend/svelte/client/src/components/Layout.svelte
<script lang="ts">
  import { Route, Link } from 'svelte-routing'
  import Home from '../pages/Home.svelte'
  import About from '../pages/About.svelte'
</script>

<div class="app">
  <header class="header">
    <nav>
      <Link to="/">Home</Link>
      <Link to="/about">About</Link>
    </nav>
  </header>
  <main class="main">
    <Route path="/" component={Home} />
    <Route path="/about" component={About} />
  </main>
  <footer class="footer">
    <p>Built with Mizu + Svelte</p>
  </footer>
</div>
