// cmd/cli/templates/frontend/react/client/src/pages/About.tsx
function About() {
  return (
    <div className="page about">
      <h1>About</h1>
      <p>
        This is a React SPA powered by Mizu, a lightweight Go web framework.
      </p>
      <ul>
        <li>React 18 with TypeScript</li>
        <li>Vite for fast development and optimized builds</li>
        <li>React Router for client-side routing</li>
        <li>Mizu backend with the frontend middleware</li>
      </ul>
    </div>
  )
}

export default About

// cmd/cli/templates/frontend/spa/svelte/client/src/pages/About.svelte
<div class="page about">
  <h1>About</h1>
  <p>
    This is a Svelte SPA powered by Mizu, a lightweight Go web framework.
  </p>
  <ul>
    <li>Svelte 5 with TypeScript</li>
    <li>Vite for fast development and optimized builds</li>
    <li>svelte-routing for client-side routing</li>
    <li>Mizu backend with the frontend middleware</li>
  </ul>
</div>
