// cmd/cli/templates/frontend/react/client/src/pages/Home.tsx
import { useState, useEffect } from 'react'

function Home() {
  const [message, setMessage] = useState<string>('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetch('/api/hello')
      .then(res => res.json())
      .then(data => {
        setMessage(data.message)
        setLoading(false)
      })
      .catch(() => setLoading(false))
  }, [])

  return (
    <div className="page home">
      <h1>Welcome</h1>
      {loading ? (
        <p>Loading...</p>
      ) : (
        <p className="api-message">{message}</p>
      )}
    </div>
  )
}

export default Home

// cmd/cli/templates/frontend/spa/svelte/client/src/pages/Home.svelte
<script lang="ts">
  import { onMount } from 'svelte'

  let message = $state('')
  let loading = $state(true)

  onMount(async () => {
    try {
      const res = await fetch('/api/hello')
      const data = await res.json()
      message = data.message
    } catch {
      message = 'Failed to load message'
    } finally {
      loading = false
    }
  })
</script>

<div class="page home">
  <h1>Welcome</h1>
  {#if loading}
    <p>Loading...</p>
  {:else}
    <p class="api-message">{message}</p>
  {/if}
</div>
